version: 2.1

parameters:
  deploy_target:
    type: enum
    default: dev
    enum: ["dev", "stage", "production"]

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "build"
          command: "echo Build Successful."
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: "echo Deploy to << pipeline.parameters.deploy_target >>"


workflows:
  deploy-demo:
    jobs:
      - build
      - deploy